[project]
name = "hugging-face-text-classification"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "datasets==3.6.0",
    "scikit-learn>=1.7.2",
    "soundfile>=0.13.1",
    "speechbrain>=1.0.3",
    "torch>=2.8.0",
    "transformers[torch]>=4.57.0",
]
